[project]
name = "lab15"
version = "0.1.0"
description = "BST implementation"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pytest>=9.0.2"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
lab15 = { workspace = true }